### ISSUE TITLE
General-purpose documentation (Swagger / Sphinx / Readthedocs, etc)

### ISSUE THREAD

**Issue by joeflack4** [PMA-2020/pma-api#4]
### 1. Decide on implementation
**Options**
- Readthedocs
- Something home-grown

#### 2.2 Add new documentation
- 2.2.1 Add new docs to new implementation
- 2.2.1 Add new docs to new GitHub readme

#### 5.1 Searchability
If you want full support for searching inside your Read the Docs site you will need to install [Elasticsearch](https://www.elastic.co/products/elasticsearch).

#### 5.2 Mimetype routing
Route the request to /docs or /rest depending on mimetype.

## Task List
- [x] 1. Decide on implementation (e.g. Open API / Swagger spec)
- [x] 2. Create docs
- [x] 2.5 Optional: Add Open API / Swagger docs
- [x] 3. Host docs (local vs otherwise)
- [x] 4. Set up process to update docs as new releases are made
- [x] 5. Optional: Bonus steps

**Comment by joeflack4** [comment]
Finished.
